export const CRITERIA_KEYS = [
  'fakery',
  'door_sills_protrude',
  'parking_cam_mud',
  'key_design_weight',
  'acceleration',
  'brake',
  'eco',
  'build',
  'driver_s_display_easy',
  'driver_s_display_bright',
  'infotainment_responsive',
  'infotainment_bright',
  'infotainment_parking_cam',
  'infotainment_a_c_control',
  'infotainment_vol_control',
  'centre_cubby',
  'doorbins_front',
  'doorbins_back',
  'cup_holder',
  'glovebox',
  'charging_ports',
  'seatback_pocket',
  'sunglass_storage',
  'driver_seat_pos_shape_mtr',
  'driver_seat_adjustment',
  'steering_adjustment',
  'suspension',
  'insulation',
  'engine_noise',
  'body_roll',
  'backseat_headroom',
  'backseat_kneeroom',
  'backseat_incline',
  'backseat_deep_footwell',
  'backseat_flat_floor',
  'backseat_isofix',
  'backseat_armrest_cover',
  'backseat_seat_belts_pos',
  'backseat_rear_windows_roll',
  'rear_a_c_port_climate',
  'boot_lip',
  'flat_boot',
  'easily_foldable_seats',
  'load_cover_fits_inside',
  'ncap',
  'reliable',
  'visibility_side_mirrors',
  'visibility_irvm_back',
  'visibility_pillars',
  'handling',
] as const;

export type CriterionKey = (typeof CRITERIA_KEYS)[number];

export const CRITERIA_LABELS: Record<CriterionKey, string> = {
  fakery: 'Honest design (no fake vents/exhaust)',
  door_sills_protrude: 'Easy entry/exit (door sills)',
  parking_cam_mud: 'Camera stays clean in bad weather',
  key_design_weight: 'Key feel and build quality',
  acceleration: 'Acceleration',
  brake: 'Braking confidence',
  eco: 'Fuel/energy efficiency',
  build: 'Build quality and solidity',
  driver_s_display_easy: 'Driver display clarity',
  driver_s_display_bright: 'Driver display brightness',
  infotainment_responsive: 'Infotainment responsiveness',
  infotainment_bright: 'Infotainment screen brightness',
  infotainment_parking_cam: 'Parking camera quality',
  infotainment_a_c_control: 'Climate control accessibility',
  infotainment_vol_control: 'Volume control accessibility',
  centre_cubby: 'Centre console storage',
  doorbins_front: 'Front door storage',
  doorbins_back: 'Rear door storage',
  cup_holder: 'Cup holders',
  glovebox: 'Glovebox',
  charging_ports: 'Charging ports',
  seatback_pocket: 'Seatback pockets',
  sunglass_storage: 'Sunglass storage',
  driver_seat_pos_shape_mtr: 'Driver seat comfort and support',
  driver_seat_adjustment: 'Seat adjustment range',
  steering_adjustment: 'Steering wheel adjustment',
  suspension: 'Ride comfort (suspension)',
  insulation: 'Cabin insulation',
  engine_noise: 'Engine refinement',
  body_roll: 'Body control in corners',
  backseat_headroom: 'Rear headroom',
  backseat_kneeroom: 'Rear legroom',
  backseat_incline: 'Rear seat recline',
  backseat_deep_footwell: 'Rear foot space',
  backseat_flat_floor: 'Flat rear floor',
  backseat_isofix: 'ISOFIX child seat anchors',
  backseat_armrest_cover: 'Rear armrest',
  backseat_seat_belts_pos: 'Rear seat belt positioning',
  backseat_rear_windows_roll: 'Rear windows open fully',
  rear_a_c_port_climate: 'Rear climate and charging',
  boot_lip: 'Low boot/cargo lip',
  flat_boot: 'Flat cargo floor',
  easily_foldable_seats: 'Easy-folding rear seats',
  load_cover_fits_inside: 'Load cover stows neatly',
  ncap: 'Safety rating (NCAP)',
  reliable: 'Reliability',
  visibility_side_mirrors: 'Side mirror visibility',
  visibility_irvm_back: 'Rear-view mirror visibility',
  visibility_pillars: 'Pillar visibility (blind spots)',
  handling: 'Handling precision',
};

/**
 * Maps each criterion to the scoring category it contributes to.
 * Used by both derivePreferences (to compute category weights) and
 * scoreCars (to derive weights from criteriaImportance).
 */
export const CRITERIA_CATEGORIES: Record<string, readonly CriterionKey[]> = {
  safety: [
    'ncap', 'reliable', 'visibility_side_mirrors', 'visibility_irvm_back',
    'visibility_pillars', 'backseat_isofix', 'backseat_seat_belts_pos',
    'infotainment_parking_cam',
  ],
  technology: [
    'driver_s_display_easy', 'driver_s_display_bright', 'infotainment_responsive',
    'infotainment_bright', 'infotainment_a_c_control', 'infotainment_vol_control',
    'charging_ports', 'parking_cam_mud', 'key_design_weight', 'build', 'fakery',
  ],
  space: [
    'centre_cubby', 'doorbins_front', 'doorbins_back', 'cup_holder', 'glovebox',
    'seatback_pocket', 'sunglass_storage', 'backseat_headroom', 'backseat_kneeroom',
    'backseat_incline', 'backseat_deep_footwell', 'backseat_flat_floor',
    'backseat_armrest_cover', 'backseat_rear_windows_roll', 'rear_a_c_port_climate',
    'boot_lip', 'flat_boot', 'easily_foldable_seats', 'load_cover_fits_inside',
    'door_sills_protrude',
  ],
  performance: [
    'acceleration', 'brake', 'handling', 'suspension', 'body_roll', 'engine_noise',
    'insulation', 'driver_seat_pos_shape_mtr', 'driver_seat_adjustment',
    'steering_adjustment', 'eco',
  ],
};
